#!/bin/bash

CURRENT_LAYOUT=`setxkbmap -print | awk -F"+" '/xkb_symbols/ {print $2}'`

if [ $CURRENT_LAYOUT = "us" ]; then
	setxkbmap il
	xmodmap ~/.Xmodmap_heb
elif [ $CURRENT_LAYOUT = "il" ]; then
	setxkbmap us
	xmodmap ~/.Xmodmap
else
	echo "Unknown layout"
fi
